version: "3"

services:
  app:
    build:
      context: ./project_name/
      dockerfile: ../docker/Dockerfile.dev
    tty: true
    volumes:
      - "./data/input:/workspace/input/"
      - "./data/output:/workspace/output/"
      - "./project_name:/workspace/project_name/"
